apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnist-web
  namespace: default
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: mnist-web
  template:
    metadata:
      labels:
        app: mnist-web
    spec:
      containers:
        - name: mnist-web
          image: dongjekim1030/mnist-web:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: mnist-web
  namespace: default
  labels:
    app: mnist-web
spec:
  selector:
    app: mnist-web
  ports:
    - port: 5173
      targetPort: 5173
      name: web
  type: ClusterIP